<?php
$titolo = "PRIVACY POLICY";
// Includi head.php
require_once 'head.php';
?>
    <h1><?php echo ($titolo)?></h1>

    <h3>Effective Date: February 07, 2024</h3>
    <p>Gray Design s.r.l. and its affiliate companies ("Gray Design," "we," "us" or "our") recognizes the importance of protecting the privacy of our online visitors. It is our intent to balance our legitimate business interests in collecting and using information received from and about you with your reasonable expectations of privacy. The following privacy policy ("Privacy Policy") is the way we handle information learned about you from your visits to our website available at https://www.moxfield.com (the "Service").
    </p>
    <p>PLEASE REVIEW THIS PRIVACY POLICY CAREFULLY. When you submit information to or through the Service, you consent to the collection and processing of your information as described in this Privacy Policy. By using the Service, you accept the terms of this Privacy Policy and our Terms of Use, and consent to our collection, use, disclosure and retention of your information as described in this Privacy Policy. We, and our Service visitors, are bound by laws in the United States. IF YOU DO NOT AGREE WITH ANY PART OF THIS PRIVACY POLICY, YOU ARE NOT AUTHORIZED TO USE THE SERVICE.
    </p>
    <h3>Information Collected Automatically</h3>
    <p>Information about your device hardware and software is automatically collected by Moxfield when you use the Service. This information may include: your IP address, browser type, domain names, access times, geographic location, referring website addresses and other technical information such as protocol status and sub-status, bytes sent and received, and server information. We may also collect information about how you interact with the Service. This information is used by Moxfield for its business purposes, including for the operation and improvement of the Service, for technical troubleshooting, to maintain quality of the Service and to provide general statistics regarding use of the Service.
    </p>
    <p>We may use third-party advertising companies to serve ads when you use the Service. These companies may use aggregated information (not including your name, address, email address or telephone number) about your visits to this and other Web sites in order to provide advertisements about goods and services of interest to you. If you would like more information about this practice and to know your choices about not having this information used by these companies,click here.
    </p>
    <h3>Cookies and Other Information Collection Tools</h3>
    <p>What are cookies? A cookie is a small file containing a string of characters that is sent to your computer when you visit a website or use an online service. When you visit the website or use the service again, the cookie allows that website or online service to recognize your browser or device. Cookies may store unique identifiers, user preferences and other information.
    </p>
    <p>Why do we use them? Cookies help us improve the Service by providing us with information about which parts of the Service are most popular, enabling us to analyze technical and navigational information about the Service, and helping us to detect and prevent fraud. We also use cookies and other data collection tools (such as web beacons and server logs) to help improve your experience with the Service. For example, we use analytics services to help analyze how users use the Service. These tools use cookies to collect standard Internet log information and visitor behavior information in an anonymous form. The information generated by the cookie about your use of the Service (including IP address) is transmitted to our data collection tool service providers. This information is then used by us to evaluate visitors' use of the Service and to compile statistical reports on website activity for Moxfield. We also may use third party advertisements on the Service. Some of these advertisers may use technology such as cookies and web beacons when they advertise on the Service, which will also send these advertisers (such as Google through the Google AdSense program) information including your IP address, your ISP, the browser you used to visit our site, and in some cases, whether you have Flash installed. This is generally used for geotargeting purposes or showing certain ads based on specific sites visited (such as showing cooking ads to someone who frequents cooking sites).
    </p>
    <p>How do I control cookies? Web browsers allow some control of most cookies through the browser settings. To find out more about cookies, including how to manage and delete cookies, visit www.allaboutcookies.org. Some web browsers provide settings that allow a user to reject cookies or to alert a user when a cookie is placed on the user's computer, tablet or mobile device. Most mobile devices also offer settings to reject mobile device identifiers. Although users are not required to accept cookies or mobile device identifiers, blocking or rejecting them may prevent access to some features available through the Service.
    </p>
    <h3>Security</h3>
    <p>The security of your Personal Information is important to us, but remember that no method of transmission over the Internet, or method of electronic storage, is 100% secure. While we strive to use commercially acceptable means to protect your Personal Information, we cannot guarantee its absolute security.
    </p>

    <h3>Links to External Websites</h3>
    <p>Our Service may contain links to third party websites. Any access to and use of such third party websites is not governed by this Privacy Policy, but is instead governed by the privacy policies of those third party websites, and we are not responsible for the information practices of such third party websites.
    </p>
    <h3>Do Not Track</h3>
    <p>Our Service does not currently take any action when it receives a Do Not Track request. Do Not Track is a privacy preference that you can set in your web browser to indicate that you do not want certain information about your webpage visits collected across websites when you have not interacted with that service on the page. For details, including how to turn on Do Not Track, visit https://allaboutdnt.com/.
    </p>
    <h3>Questions</h3>
    <p>If you have any questions regarding this Privacy Policy, please contact us at graydesign@info.com.
    </p>
    <h3>Notification of Changes</h3>
    <p>Any changes to our Privacy Policy will be posted to this page so users are always aware of the information we collect and how we use it. Accordingly, please refer back to this Privacy Policy frequently as it may change.
    </p>

<?php
// Includi footer.php
require_once 'footer.php';
?>